FROM node:18-alpine

WORKDIR /app/frontend

# Instalar dependencias
COPY frontend/package*.json ./
RUN npm install

# Copiar el código
COPY frontend/ .

# Comando para desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]